---
- name: DTR | Uninstall controller
  shell: docker run -it --rm docker/dtr:{{ DTR_VERSION }} destroy --ucp-insecure-tls
  ignore_errors: yes
  when: dtr_leader is defined or dtr_replica is defined
