---
- name: UCP | Uninstall controller
  become: true
  shell: docker container run --rm -v /var/run/docker.sock:/var/run/docker.sock docker/ucp:{{ UCP_VERSION }} uninstall-ucp
  ignore_errors: yes
  when: ucp_leader is defined
