---

# Install Docker EE
- hosts: all
  roles:
  - role: install-docker
  tags:
  - daemon

# Install UCP
- hosts: ucp
  serial: 1
  roles:
  - role: install-ucp
  tags:
  - ucp

# Install DTR
- hosts: dtr
  serial: 1
  roles:
  - role: install-dtr
  tags:
  - dtr
